version: "3"

services:
  front-end:
    build: ./front_end
    ports:
      - "3000:3000"
    #uncomment for development
    volumes:
      - "./front_end:/app"
  back-end:
    build: .
    environment:
      - NODE_ENV=development
      - MSG_USER=guest
      - MSG_PASS=guest
      - MESSAGING_HOST=messaging  
      - PYTHONUNBUFFERED=1
